apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
    - name: redis
      image: mkbn/redis:v1.0
      ports:
        - containerPort: 6379
          protocol: TCP
